- hosts: 127.0.0.1
  connection: local

  become: true
  become_method: su
  become_user: namth22

  tasks:
  - name: install dev tools
    apt: name="@Development tools" state=present

  - name: install x86 oracle dependencies for 11g
    apt: name={{ item }} state=present
    with_items:
      - binutils.x86_64
      - compat-libstdc++-33.x86_64
      - compat-libstdc++-33.i686
      - elfutils-libelf.x86_64
      - elfutils-libelf-devel.x86_64
      - expat.x86_64 
      - gcc.x86_64
      - gcc-c++.x86_64
      - glibc.i686
      - glibc.x86_64
      - glibc-common
      - glibc-devel
      - glibc-headers
      - libaio.x86_64
      - libaio.i686
      - libaio-devel.i686
      - libaio-devel.x86_64
      - libgcc.i686
      - libgcc.x86_64
      - libstdc++.x86_64
      - libstdc++.i686
      - libstdc++-devel
      - make
      - numactl
      - ksh
      - sysstat.x86_64
      - xorg-x11-xauth.x86_64
    when: oracle_version | regex_replace ('^([0-9]{1,2}.[0-9]{1,}.[0-9]{1,})(.*)$','\g<1>') == "11.2.0"
    become: true
    become_method: su
    become_user: namth22

# ansible-playbook -i hosts --extra-vars='ansible_ssh_user=namth22 ansible_ssh_pass=nam123456 ansible_become_pass=nam123456' install-packages.yml